### ISSUE TITLE
typo of the paper

### ISSUE THREAD

**Issue by wanglong001** [Torchlight-ljj/HigeNet#1]
thank you for opening source

and I reading your paper, I found a typo
please check it out
I shouldn't have misunderstood

----

![image](https://user-images.githubusercontent.com/14817376/204984623-3d6ecbd9-4e06-47c9-9c4a-1a6f1a631853.png)

**Comment by Torchlight-ljj** [comment]
Hi,
I am Jiajia. Hope your doing well. Thank for your pointing out this mistake, it should be Conv1d(A+K)  and I will update this later.
Best regards.
Jiajia.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: 2022年12月1日 14:58
To: ***@***.***>
Cc: ***@***.***>
Subject: [Torchlight-ljj/HigeNet] typo of the paper (Issue #1)


thank you for opening source

and I reading your paper, I found a typo
please check it out
I shouldn't have misunderstood


[image]<https://user-images.githubusercontent.com/14817376/204984623-3d6ecbd9-4e06-47c9-9c4a-1a6f1a631853.png>

**Comment by wanglong001** [comment]
ok, thank you for your paper
